[gitea]
version = "1.24.2"
repo = "go-gitea/gitea"

[jenkins]
version = "2.492.3"
repo = "jenkinsci/jenkins"

[nginx_proxy_manager]
version = "2.12.3"
repo = "NginxProxyManager/nginx-proxy-manager"

[harbor]
version = "2.11.1"
repo = "goharbor/harbor"

[wiki-js]
version = "2.5.307"
repo = "Requarks/wiki"

[keycloak]
version = "26.1.4"
repo = "keycloak/keycloak"

[dragonfly]
version = "1.27.1"
repo = "dragonflydb/dragonfly"

[elastalert]
version = "2.8.0"
repo = "jertel/elastalert2"

[logstash]
version = "8.5.2-1"
repo = "elastic/logstash"

[kibana]
version = "8.5.2"
repo = "elastic/kibana"

[elasticsearch]
version = "8.5.2"
repo = "elastic/elasticsearch"

[sonarqube]
version = "25.5.0.107428"
repo = "SonarSource/sonarqube"

[pi-hole-core]
version = "6.0.6"
repo = "pi-hole/pi-hole"

[pi-hole-ftl]
version = "6.1"
repo = "pi-hole/FTL"

[zulip]
version = "10.2"
repo = "zulip/zulip"
